### ISSUE TITLE
HTTP Error 401: Unauthorized on controller version 4.6.4

### ISSUE THREAD

**Issue by dodgythoughts** [unifi-hackers/unifi-lab#17]
Installed a new controller 
old controller v 3.2.1
new controller v 4.6.4

getting the below error when attempting to use the script.

sysadmin@unifi:/etc/unifi_lab$ /etc/init.d/unifi_lab start
 * Starting Ubiquiti UniFi Lab unifi_lab                                                                                                                                                                                                     installing handler for correct redirect
Traceback (most recent call last):
  File "/usr/lib/unifi_lab/unifi_lab.py", line 428, in <module>
    main()
  File "/usr/lib/unifi_lab/unifi_lab.py", line 412, in main
    myUniFiLab = UniFiLab(myConfigManager)
  File "/usr/lib/unifi_lab/unifi_lab.py", line 157, in __init__
    self._stationList = self._ctlr.ctlr_stat_sta()
  File "/usr/lib/unifi_lab/unifi_lab_ctlrobj.py", line 104, in ctlr_stat_sta
    return self.curl("api/stat/sta")
  File "/usr/lib/unifi_lab/unifi_lab_ctlrobj.py", line 64, in curl
    uo=urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by matsimon** [comment]
Hi @dodgythoughts this is due to the fact that unifi-lab has been (as marked in the description) dormant and never been made compatible with anything greater than unifi v2.x

I recommend you to give http://github.com/calmh/unifi-api a look, where I ported some of the method from unifi-lab to it, as well as (back then) the v3 compatibility. Its code is cleaner and well documented, and should have recently received v4 compatibility.

However this code drop by Ubiquiti still has some nits and pointers that may not yet be implemented by unifi-api (ported some parts over to this other library, but I don't think all of them).

**Comment by zFr3eak** [comment]
Hello,

I am experiencing exact the same issue. I am using the latest unifi-api and choose as version v4. 
My controller firmware is: v4.6.4

Any idea how to fix this ?

Thanks

**Comment by matsimon** [comment]
@zFr3eak Please read my answer from May. The authentication scheme from UniFi has changed starting v3 and slightly with v4, both with unifi-lab hasn't been made compatible with.

Personally I don't have an interest to make that happen as I use unifi-api nowadays which Is cleaner to use. If you need a feature from unifi-lab that unifi-api doesn't implement, please tell me and I'll look to make that ported over to it as I've done in the past.

Scripting with unif-api turned out to be quicker and cleaner overall.

**Comment by zFr3eak** [comment]
@matsimon I think you missunderstood me. I am already using the latest UNIFI-API and experiencing this issue. I've never used unifi-lab ! 

Any idea ?

**Comment by matsimon** [comment]
@zFr3eak  Then you are actually reporting to the wrong project since unifi-api is at calmh/unifi-api and unifi-lab is not using unifi-api.

I don't have a v4 controller at hand, but it looks like you're seeing what was already reported at
https://github.com/calmh/unifi-api/issues/31

Remember that unifi-api, as of writing will use the v2 API URL if no version is specified and will use the v2 behaviour. You need to specify v4 when initializing the controller in Python.
https://github.com/calmh/unifi-api/blob/master/unifi/controller.py#L140-L141

**Comment by zFr3eak** [comment]
@matsimon Oh my fault, i haven't realized that this sthe wrong project. I know that i have to instantiate the controller with v4 in order to use it, but anyway i am getting this error. I already tried to uninstall and reinstall the unifi-api but i am running into the same issue.

**Comment by JokinAU** [comment]
Kudos @matsimon, I only had to change the constructor from:
def __init__(self, host, username, password, port=8443, version='v2', site_id='default'):
to
def __init__(self, host, username, password, port=8443, version='v4', site_id='default'):
And everything started to work again!

**Comment by matsimon** [comment]
OK @JokinAU - I'm all open to take patches, however I'd prefer to have it as parameter that can be provided, not a hardcoded value. 

Next step wouid be to add capability to provide the site name other than default.
(I'd even be ok to break v2 compatibility I guess we can consider it obsolete by now)
